config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  resources :boards do
    resources :lists do 
      resources :tasks
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :lists
  
  def self.by_message
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only:[:show, :edit, :update, :destroy]
  def index
    @boards = Board.all
  end

  def show
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(params_board)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(params_board)
      redirect_to boards_path
    else 
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end
  
  def params_board
    params.require(:board).permit(:message, :id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :update, :edit, :destroy]
  before_action :set_board
  def index
    @lists = @board.lists.all
  end

  def show
    
  end

  def new
    @list = @board.lists.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @list = @board.lists.new(list_params)

    if @list.save
      redirect_to board_lists_path
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to board_lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:todo, :board_id)
  end

  def set_board
    @board = Board.find(params[:board_id])
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_for @board do |f| %>
  <%= f.label :message %>
  <%= f.text_field :message %>

  <%= f.submit %>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>
<hr />
<%= render 'form' %>

app/views/boards/index.html.erb
<h1>Main Job Board</h1>
<%= link_to 'Create Board', new_board_path %>
<hr />
<% @boards.each do |board| %>
  <ul>
  <h3><%= board.message %></h3>
    <li><%= link_to 'To do list', board_lists_path(board.id) %></li>
    <li><%= link_to 'Edit', edit_board_path(board.id) %></li>
    <li><%= link_to 'Delete', board_path(board.id), method: :delete %></li>
  </ul>
<% end %>

app/views/boards/new.html.erb
<h1> Create New Board </h1>
<hr />
<%= render 'form' %>

app/views/boards/show.html.erb
<h1>Boards#show</h1>
<p>Find me in app/views/boards/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<%= link_to 'Main Board', boards_path %>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTrollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for [@board, @list] do |f| %>
    <%= f.label :todo %>
    <%= f.text_field :todo %>
    <%= f.submit %>
  <% end %>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>To Do List</h1>
  <%= link_to 'New Todo', new_board_list_path %>
<hr />
<% @lists.each do |list| %>
<ol>
  <li><%= list.todo %></li>
</ol>
<% end %>

app/views/lists/new.html.erb
<h1> Create New Todo </h1>
<hr />
<%= render 'form' %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>